repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ['--maxkb=52428'] # Max github size before warning
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.3.0
    hooks:
    -   id: black
        language_version: python3.9.17
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: [--extend-ignore, E501]
        exclude: "__init__.py"
-   repo: https://github.com/crate-ci/typos.git
    rev: v1.19.0
    hooks:
    -   id: typos
        exclude: ".ipynb"
