channels:
  - zeroae
  - conda-forge
dependencies:
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.8.0.121
  - cython=0.29.33
  - numpy=1.24.1
  - lightning=2.2.1
  - ipykernel=6.26.0
  - ipython=8.18.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.8.0
  - pandas=1.5.2
  - python=3.9.17
  - python_abi=3.9
  - pytorch_cluster=1.6.0
  - pytorch_scatter=2.1.1
  - pytorch_sparse=0.6.16
  - pytorch_geometric=2.5.3
  - pytorch=1.13.1
  - pytorch-gpu=1.13.1
  - rdkit=2023.09.1
  - rich=12.6.0
  - scikit-learn=1.2.1
  - torchvision=0.14.1
  - tensorboard=2.11.2
  - typing-extensions=4.4.0
  - einops=0.7.0
  - addict=2.4.0
  - pip:
    - jaxtyping
    - yapf
    - tensorboardX
